# Generated by Django 2.2.7 on 2019-11-19 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombreCompleto', models.CharField(max_length=30)),
                ('correoElectronico', models.EmailField(max_length=30)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('direccion', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=25)),
                ('tipoPersona', models.CharField(default='Usuario', max_length=50)),
            ],
        ),
    ]
