# Generated by Django 2.2.7 on 2019-11-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': (('administrador', 'Es administrador'), ('cliente', 'Es cliente'))},
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
